version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d fitness_db" ]
      interval: 5s
      timeout: 5s
      retries: 10

  ingestion_api:
    build:
      context: ./ingestion_api
      dockerfile: Dockerfile
    container_name: ingestion-api
    command: python api.py
    ports:
      - "8081:8081"
    volumes:
      - ./ingestion_api:/app
    working_dir: /app
    depends_on:
      postgres:
        condition: service_healthy

  data_source_1:
    build:
      context: ./data_sources
      dockerfile: Dockerfile
    container_name: data_source_1
    command: python run_data_source_1.py
    volumes:
      - ./data_sources:/app
    working_dir: /app
    depends_on:
      - ingestion_api

  data_source_2:
    build:
      context: ./data_sources
      dockerfile: Dockerfile
    container_name: data_source_2
    command: python run_data_source_2.py
    volumes:
      - ./data_sources:/app
    working_dir: /app
    depends_on:
      - ingestion_api

  data_source_3:
    build:
      context: ./data_sources
      dockerfile: Dockerfile
    container_name: data_source_3
    command: python run_data_source_3.py
    volumes:
      - ./data_sources:/app
    working_dir: /app
    depends_on:
      - ingestion_api

volumes:
  pgdata: